### ISSUE TITLE
Detect only first object from same class

### ISSUE THREAD

**Issue by grosmar** [rcaceiro/node-yolo#4]
Hey,

Your tool is awesome! :)

But found a bug: If I try to detect a picture where I have two person on it, it only detects the one of them.
If I have multiple objects with different classes it works well (dog, bicycle, etc).

Do you have any idea why?

**Comment by rcaceiro** [comment]
@grosmar thank you for the compliment.
I found that bug too it is related with a verification that we do, this bug was fixed already on version 2.0.0, that is currently under development and is no backwards compatible. 
I intend to launch the next version tomorrow, the branch already exists on [v2.0.0](https://github.com/rcaceiro/node-yolo/tree/v2.0.0) and the fix to version 1.x.x in the caseof someone do not wan't to change the setup.

**Comment by grosmar** [comment]
Thanks!

Waiting for the new release then! :)

**Comment by rcaceiro** [comment]
I already released the both releases.
Please be carefull if use npm because the version 2.0.0 isn't backwards compatible with version 1.x.x
If you want use version 1.x.x change the version to 1.2.5 on packege.json, if you use the flagship one do the update.
